import type { Annotation, Paper } from '@/lib/db/types';
import { getAnnotationTypeLabel } from '@/lib/annotation/service';

export interface ExportData {
  paper: Paper;
  annotations: Annotation[];
  aiSummary: any;
  researchNotes: string;
}

export function generateMarkdown(data: ExportData): string {
  const { paper, annotations, aiSummary, researchNotes } = data;
  const authors = Array.isArray(paper.authors)
    ? paper.authors
    : typeof paper.authors === 'string'
      ? JSON.parse(paper.authors)
      : [];
  const byType = (type: Annotation['type']) => annotations.filter((annotation) => annotation.type === type);
  
  let markdown = `# ${paper.title}\n\n`;
  markdown += `> PaperWeave 精读导出 · ${new Date().toLocaleDateString('zh-CN')}\n\n`;
  
  markdown += `## 1. 论文信息\n\n`;
  if (authors.length > 0) {
    markdown += `**Authors:** ${authors.map((a: any) => a.name).join(', ')}\n\n`;
  }
  if (paper.publishedAt) {
    markdown += `**Published:** ${new Date(paper.publishedAt).toLocaleDateString('zh-CN')}\n\n`;
  }
  if (paper.sourceUrl) {
    markdown += `**Source:** [Link](${paper.sourceUrl})\n\n`;
  }
  if (paper.arxivId) {
    markdown += `**arXiv ID:** ${paper.arxivId}\n\n`;
  }
  markdown += `**Annotations:** ${annotations.length} total · ${byType('highlight').length} highlights · ${byType('insight').length} insights · ${byType('todo').length} todos · ${byType('transferable').length} transferable\n\n`;
  
  markdown += `---\n\n`;
  
  if (aiSummary) {
    markdown += `## 2. AI 解释\n\n`;
    if (aiSummary.coreIdea) {
      markdown += `### Core Idea\n\n${aiSummary.coreIdea}\n\n`;
    }
    if (aiSummary.relatedConcepts) {
      markdown += `### Related Concepts\n\n${aiSummary.relatedConcepts}\n\n`;
    }
    if (aiSummary.whyItMatters) {
      markdown += `### Why It Matters\n\n${aiSummary.whyItMatters}\n\n`;
    }
    if (aiSummary.applications) {
      markdown += `### Potential Applications\n\n${aiSummary.applications}\n\n`;
    }
    markdown += `---\n\n`;
  }
  
  const highlights = byType('highlight');
  if (highlights.length > 0) {
    markdown += `## 3. 关键高亮\n\n`;
    highlights.forEach((annotation, index) => {
      markdown += `${index + 1}. ${annotation.selectedText || '(无文本)'}\n`;
      if (annotation.comment) {
        markdown += `   > ${annotation.comment}\n`;
      }
      markdown += `   *Page ${annotation.page + 1}*\n\n`;
    });
    markdown += `---\n\n`;
  }
  
  const insights = byType('insight');
  if (insights.length > 0) {
    markdown += `## 4. 研究洞察\n\n`;
    insights.forEach((annotation, index) => {
      markdown += `### Insight ${index + 1}\n\n`;
      markdown += `**Text:** ${annotation.selectedText || '(无文本)'}\n\n`;
      if (annotation.comment) {
        markdown += `**Comment:** ${annotation.comment}\n\n`;
      }
      markdown += `*Page ${annotation.page + 1}*\n\n`;
    });
    markdown += `---\n\n`;
  }
  
  const transferable = byType('transferable');
  if (transferable.length > 0) {
    markdown += `## 5. 可迁移想法\n\n`;
    transferable.forEach((annotation, index) => {
      markdown += `${index + 1}. ${annotation.selectedText || '(无文本)'}\n`;
      if (annotation.comment) {
        markdown += `   > ${annotation.comment}\n`;
      }
      markdown += `   *Page ${annotation.page + 1}*\n\n`;
    });
    markdown += `---\n\n`;
  }
  
  const todos = byType('todo');
  if (todos.length > 0) {
    markdown += `## 6. 后续 TODO\n\n`;
    todos.forEach((annotation, index) => {
      markdown += `- [ ] ${annotation.selectedText || '(无文本)'}\n`;
      if (annotation.comment) {
        markdown += `  - ${annotation.comment}\n`;
      }
      markdown += `  *Page ${annotation.page + 1}*\n`;
    });
    markdown += `\n---\n\n`;
  }
  
  if (researchNotes && researchNotes.trim()) {
    markdown += `## 7. 我的研究笔记\n\n${researchNotes}\n\n`;
    markdown += `---\n\n`;
  }
  
  markdown += `*Generated by PaperWeave Research Workspace*\n`;
  
  return markdown;
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
