import type { Annotation, Author, Paper, StickyNote } from '@/lib/db/types';

/** AI「解释选区」结构化结果（各字段可缺省） */
export interface AISummary {
  coreIdea?: string;
  relatedConcepts?: string;
  whyItMatters?: string;
  applications?: string;
}

export interface ExportData {
  paper: Paper;
  annotations: Annotation[];
  researchNotes: string;
  /** 页面便签（📒），可选——按页码排序导出 */
  stickyNotes?: StickyNote[];
}

export function generateMarkdown(data: ExportData): string {
  const { paper, annotations, researchNotes, stickyNotes = [] } = data;
  // AI 解释现逐条挂在标注上（aiSummary 字段），导出时从标注汇总。
  const aiAnnotations = annotations.filter((a) => a.aiSummary);
  const authors = Array.isArray(paper.authors)
    ? paper.authors
    : typeof paper.authors === 'string'
      ? JSON.parse(paper.authors)
      : [];
  const byType = (type: Annotation['type']) => annotations.filter((annotation) => annotation.type === type);
  
  let markdown = `# ${paper.title}\n\n`;
  markdown += `> PaperWeave 精读导出 · ${new Date().toLocaleDateString('zh-CN')}\n\n`;
  
  markdown += `## 1. 论文信息\n\n`;
  if (authors.length > 0) {
    markdown += `**Authors:** ${authors.map((a: Author) => a.name).join(', ')}\n\n`;
  }
  if (paper.publishedAt) {
    markdown += `**Published:** ${new Date(paper.publishedAt).toLocaleDateString('zh-CN')}\n\n`;
  }
  if (paper.sourceUrl) {
    markdown += `**Source:** [Link](${paper.sourceUrl})\n\n`;
  }
  if (paper.arxivId) {
    markdown += `**arXiv ID:** ${paper.arxivId}\n\n`;
  }
  markdown += `**Annotations:** ${annotations.length} total · ${byType('highlight').length} highlights · ${byType('insight').length} insights · ${byType('todo').length} todos · ${byType('transferable').length} transferable\n\n`;
  
  markdown += `---\n\n`;
  
  if (aiAnnotations.length > 0) {
    markdown += `## 2. AI 解释\n\n`;
    aiAnnotations.forEach((annotation, index) => {
      const summary = annotation.aiSummary as AISummary;
      markdown += `### 解释 ${index + 1} · Page ${annotation.page + 1}\n\n`;
      if (annotation.selectedText) {
        markdown += `> ${annotation.selectedText}\n\n`;
      }
      if (summary.coreIdea) markdown += `- **核心概念：** ${summary.coreIdea}\n`;
      if (summary.relatedConcepts) markdown += `- **相关概念：** ${summary.relatedConcepts}\n`;
      if (summary.whyItMatters) markdown += `- **为什么重要：** ${summary.whyItMatters}\n`;
      if (summary.applications) markdown += `- **潜在应用：** ${summary.applications}\n`;
      markdown += `\n`;
    });
    markdown += `---\n\n`;
  }
  
  const highlights = byType('highlight');
  if (highlights.length > 0) {
    markdown += `## 3. 关键高亮\n\n`;
    highlights.forEach((annotation, index) => {
      markdown += `${index + 1}. ${annotation.selectedText || '(无文本)'}\n`;
      if (annotation.comment) {
        markdown += `   > ${annotation.comment}\n`;
      }
      markdown += `   *Page ${annotation.page + 1}*\n\n`;
    });
    markdown += `---\n\n`;
  }
  
  const insights = byType('insight');
  if (insights.length > 0) {
    markdown += `## 4. 研究洞察\n\n`;
    insights.forEach((annotation, index) => {
      markdown += `### Insight ${index + 1}\n\n`;
      markdown += `**Text:** ${annotation.selectedText || '(无文本)'}\n\n`;
      if (annotation.comment) {
        markdown += `**Comment:** ${annotation.comment}\n\n`;
      }
      markdown += `*Page ${annotation.page + 1}*\n\n`;
    });
    markdown += `---\n\n`;
  }
  
  const transferable = byType('transferable');
  if (transferable.length > 0) {
    markdown += `## 5. 可迁移想法\n\n`;
    transferable.forEach((annotation, index) => {
      markdown += `${index + 1}. ${annotation.selectedText || '(无文本)'}\n`;
      if (annotation.comment) {
        markdown += `   > ${annotation.comment}\n`;
      }
      markdown += `   *Page ${annotation.page + 1}*\n\n`;
    });
    markdown += `---\n\n`;
  }
  
  const todos = byType('todo');
  if (todos.length > 0) {
    markdown += `## 6. 后续 TODO\n\n`;
    todos.forEach((annotation) => {
      markdown += `- [ ] ${annotation.selectedText || '(无文本)'}\n`;
      if (annotation.comment) {
        markdown += `  - ${annotation.comment}\n`;
      }
      markdown += `  *Page ${annotation.page + 1}*\n`;
    });
    markdown += `\n---\n\n`;
  }
  
  const notedStickies = stickyNotes.filter((note) => note.content.trim());
  if (notedStickies.length > 0) {
    markdown += `## 7. 页面便签 📒\n\n`;
    [...notedStickies]
      .sort((a, b) => a.page - b.page || a.y - b.y)
      .forEach((note) => {
        markdown += `- ${note.content.trim().replace(/\n/g, '\n  ')}\n`;
        markdown += `  *Page ${note.page + 1}*\n\n`;
      });
    markdown += `---\n\n`;
  }

  if (researchNotes && researchNotes.trim()) {
    markdown += `## 8. 我的研究笔记\n\n${researchNotes}\n\n`;
    markdown += `---\n\n`;
  }
  
  markdown += `*Generated by PaperWeave Research Workspace*\n`;
  
  return markdown;
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
