/**
 * 论文模拟数据（用于演示和开发环境）
 */

export const mockPapers = [
  {
    id: 'mock-1',
    title: 'Attention Is All You Need',
    abstract: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
    authors: [
      { name: 'Ashish Vaswani', affiliation: 'Google Brain' },
      { name: 'Noam Shazeer', affiliation: 'Google Brain' },
      { name: 'Niki Parmar', affiliation: 'Google Research' },
    ],
    sourceType: 'ARXIV' as const,
    sourceUrl: 'https://arxiv.org/abs/1706.03762',
    arxivId: '1706.03762',
    pdfPath: 'https://arxiv.org/pdf/1706.03762.pdf',
    publishedAt: '2017-06-12T00:00:00.000Z',
    tags: ['NLP', 'Transformer', 'Attention'],
    direction: '自然语言处理',
    summary: '传统序列模型依赖循环或卷积神经网络，本文提出了完全基于注意力机制的 Transformer 架构，摒弃了循环和卷积操作。',
    methodology: '提出多头注意力机制、位置编码、编码器-解码器架构，使用自注意力机制捕捉序列依赖关系。',
    contribution: '首次提出纯注意力机制的序列模型，成为后续所有大型语言模型的基础架构。',
    createdAt: '2024-01-15T10:00:00.000Z',
    citations: 85643,
  },
  {
    id: 'mock-2',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
    abstract: 'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.',
    authors: [
      { name: 'Jacob Devlin', affiliation: 'Google AI' },
      { name: 'Ming-Wei Chang', affiliation: 'Google AI' },
      { name: 'Kenton Lee', affiliation: 'Google AI' },
      { name: 'Kristina Toutanova', affiliation: 'Google AI' },
    ],
    sourceType: 'ARXIV' as const,
    sourceUrl: 'https://arxiv.org/abs/1810.04805',
    arxivId: '1810.04805',
    pdfPath: 'https://arxiv.org/pdf/1810.04805.pdf',
    publishedAt: '2018-10-11T00:00:00.000Z',
    tags: ['NLP', 'BERT', 'Pre-training'],
    direction: '自然语言处理',
    summary: '现有的语言模型大多是单向的，BERT 通过双向预训练学习更深层的语言表示，能够更好地理解上下文依赖。',
    methodology: '使用 Masked Language Model 和 Next Sentence Prediction 任务进行预训练，支持多种下游任务的微调。',
    contribution: '开创了双向预训练的先河，推动了 NLP 领域的重大进步。',
    createdAt: '2024-01-20T14:30:00.000Z',
    citations: 52341,
  },
  {
    id: 'mock-3',
    title: 'Deep Residual Learning for Image Recognition',
    abstract: 'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions.',
    authors: [
      { name: 'Kaiming He', affiliation: 'Microsoft Research' },
      { name: 'Xiangyu Zhang', affiliation: 'Microsoft Research' },
      { name: 'Shaoqing Ren', affiliation: 'Microsoft Research' },
      { name: 'Jian Sun', affiliation: 'Microsoft Research' },
    ],
    sourceType: 'ARXIV' as const,
    sourceUrl: 'https://arxiv.org/abs/1512.03385',
    arxivId: '1512.03385',
    pdfPath: 'https://arxiv.org/pdf/1512.03385.pdf',
    publishedAt: '2015-12-10T00:00:00.000Z',
    tags: ['Computer Vision', 'ResNet', 'Deep Learning'],
    direction: '计算机视觉',
    summary: '深度神经网络训练难度随层数增加而增加，本文提出残差学习框架，使训练更深的网络成为可能。',
    methodology: '引入残差连接，将网络层视为学习残差函数而非完整函数，解决梯度消失问题。',
    contribution: 'ResNet 在 ImageNet 上取得革命性突破，成为计算机视觉的基础架构。',
    createdAt: '2024-02-05T09:15:00.000Z',
    citations: 68920,
  },
  {
    id: 'mock-4',
    title: 'Generative Adversarial Networks',
    abstract: 'We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model G that captures the data distribution, and a discriminative model D that estimates the probability that a sample came from the training data rather than G.',
    authors: [
      { name: 'Ian Goodfellow', affiliation: 'University of Montreal' },
      { name: 'Jean Pouget-Abadie', affiliation: 'University of Montreal' },
      { name: 'Mehdi Mirza', affiliation: 'University of Montreal' },
    ],
    sourceType: 'ARXIV' as const,
    sourceUrl: 'https://arxiv.org/abs/1406.2661',
    arxivId: '1406.2661',
    pdfPath: 'https://arxiv.org/pdf/1406.2661.pdf',
    publishedAt: '2014-06-10T00:00:00.000Z',
    tags: ['GAN', 'Generative Models', 'Deep Learning'],
    direction: '生成模型',
    summary: '传统生成模型训练困难，本文提出对抗训练框架，通过两个模型的博弈来学习数据分布。',
    methodology: '生成器 G 和判别器 D 交替训练，G 试图生成逼真样本，D 试图区分真实和生成样本。',
    contribution: '开创了对抗生成模型的新方向，在图像生成、风格迁移等领域有广泛应用。',
    createdAt: '2024-02-10T16:45:00.000Z',
    citations: 34567,
  },
];
