// Offline asset optimizer for the medical-segmentation explainer.
//
// Why: the photographic sample assets shipped as 481px RGBA PNGs (input ~270KB,
// overlay ~210KB each × 9 samples ≈ 4.3MB), which made /tools/med-seg-explainer
// slow to load. This script re-encodes the photo-like PNGs to WebP at display
// resolution, emits a 96px gallery thumbnail and a tiny base64 LQIP blur per
// sample, relocates the heavy source PNGs out of public/, and writes a typed
// manifest the UI consumes. Binary masks (gt/pred) stay as crisp PNGs.
//
// Run:  pnpm optimize:med-seg   (idempotent — safe to re-run)

import sharp from "sharp";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const SAMPLES_DIR = path.join(ROOT, "public/med-seg/samples");
const SRC_DIR = path.join(ROOT, "med-seg-src"); // non-served source of truth
const MANIFEST = path.join(ROOT, "lib/med-seg/manifest.generated.ts");

// Photo-like PNGs that get re-encoded to WebP. Their originals are relocated to
// med-seg-src/ so re-runs stay reproducible without bloating the deploy.
const CONVERT = [
  { png: "input.png", webp: "input.webp", max: 512 },
  { png: "overlay.png", webp: "overlay.webp", max: 512 },
  { png: "edge_attn_preview.png", webp: "edge_attn_preview.webp", max: 512 },
  { png: "dwt/ll.png", webp: "dwt/ll.webp", max: 256 },
  { png: "dwt/lh.png", webp: "dwt/lh.webp", max: 256 },
  { png: "dwt/hl.png", webp: "dwt/hl.webp", max: 256 },
  { png: "dwt/hh.png", webp: "dwt/hh.webp", max: 256 },
];

const exists = (p) => fs.access(p).then(() => true).catch(() => false);

// Read from the relocated source first, otherwise from public/ (first run).
async function resolveSource(id, rel) {
  const srcPath = path.join(SRC_DIR, id, rel);
  if (await exists(srcPath)) return srcPath;
  return path.join(SAMPLES_DIR, id, rel);
}

// Move the original PNG out of public/ into med-seg-src/ (once).
async function relocateOriginal(id, rel) {
  const fromPublic = path.join(SAMPLES_DIR, id, rel);
  const toSrc = path.join(SRC_DIR, id, rel);
  if (await exists(toSrc)) {
    // Already relocated — drop any stale copy still in public/.
    if (await exists(fromPublic)) await fs.rm(fromPublic);
    return;
  }
  if (await exists(fromPublic)) {
    await fs.mkdir(path.dirname(toSrc), { recursive: true });
    await fs.rename(fromPublic, toSrc);
  }
}

async function lqip(srcPath) {
  const buf = await sharp(srcPath)
    .resize(16, 16, { fit: "inside" })
    .webp({ quality: 50 })
    .toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

async function processSample(id) {
  const outDir = path.join(SAMPLES_DIR, id);

  // 1) Re-encode photo-like PNGs to WebP, then relocate their originals.
  for (const { png, webp, max } of CONVERT) {
    const src = await resolveSource(id, png);
    const out = path.join(outDir, webp);
    await fs.mkdir(path.dirname(out), { recursive: true });
    await sharp(src)
      .resize(max, max, { fit: "inside", withoutEnlargement: true })
      .webp({ quality: 80, effort: 4 })
      .toFile(out);
    await relocateOriginal(id, png);
  }

  const inputSrc = await resolveSource(id, "input.png");
  const overlaySrc = await resolveSource(id, "overlay.png");

  // 2) Gallery thumbnail (96² cover) — keeps the 9 selector tiles + the canvas
  //    stage previews off the full-size assets.
  await sharp(inputSrc)
    .resize(96, 96, { fit: "cover" })
    .webp({ quality: 72 })
    .toFile(path.join(outDir, "thumb.webp"));

  // 3) LQIP blur placeholders for instant first paint.
  const [blurInput, blurOverlay] = await Promise.all([
    lqip(inputSrc),
    lqip(overlaySrc),
  ]);

  const meta = await sharp(inputSrc).metadata();

  const base = `/med-seg/samples/${id}`;
  return {
    id,
    w: meta.width ?? 0,
    h: meta.height ?? 0,
    input: `${base}/input.webp`,
    overlay: `${base}/overlay.webp`,
    gt: `${base}/gt.png`,
    pred: `${base}/pred.png`,
    edgeAttn: `${base}/edge_attn_preview.webp`,
    thumb: `${base}/thumb.webp`,
    dwt: {
      ll: `${base}/dwt/ll.webp`,
      lh: `${base}/dwt/lh.webp`,
      hl: `${base}/dwt/hl.webp`,
      hh: `${base}/dwt/hh.webp`,
    },
    blur: { input: blurInput, overlay: blurOverlay },
  };
}

async function main() {
  const entries = (await fs.readdir(SAMPLES_DIR, { withFileTypes: true }))
    .filter((d) => d.isDirectory() && /^s\d+$/.test(d.name))
    .map((d) => d.name)
    .sort((a, b) => Number(a.slice(1)) - Number(b.slice(1)));

  const assets = [];
  for (const id of entries) {
    process.stdout.write(`  • ${id} … `);
    assets.push(await processSample(id));
    process.stdout.write("done\n");
  }

  const file = `// AUTO-GENERATED by scripts/optimize-med-seg.mjs — do not edit by hand.
// Run \`pnpm optimize:med-seg\` to regenerate after changing the source assets.

export interface MedSegAsset {
  id: string;
  /** intrinsic size of the source photo (for next/image width/height hints) */
  w: number;
  h: number;
  input: string;
  overlay: string;
  gt: string;
  pred: string;
  edgeAttn: string;
  /** 96² gallery + canvas thumbnail */
  thumb: string;
  dwt: { ll: string; lh: string; hl: string; hh: string };
  /** base64 LQIP data URLs for placeholder="blur" */
  blur: { input: string; overlay: string };
}

export const MED_SEG_ASSETS: MedSegAsset[] = ${JSON.stringify(assets, null, 2)};
`;

  await fs.writeFile(MANIFEST, file);
  console.log(`\n✓ Wrote ${path.relative(ROOT, MANIFEST)} (${assets.length} samples)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
