// AUTO-GENERATED by scripts/optimize-med-seg.mjs — do not edit by hand.
// Run `pnpm optimize:med-seg` to regenerate after changing the source assets.

export interface MedSegAsset {
  id: string;
  /** intrinsic size of the source photo (for next/image width/height hints) */
  w: number;
  h: number;
  input: string;
  overlay: string;
  gt: string;
  pred: string;
  edgeAttn: string;
  /** 96² gallery + canvas thumbnail */
  thumb: string;
  dwt: { ll: string; lh: string; hl: string; hh: string };
  /** base64 LQIP data URLs for placeholder="blur" */
  blur: { input: string; overlay: string };
}

export const MED_SEG_ASSETS: MedSegAsset[] = [
  {
    "id": "s0",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s0/input.webp",
    "overlay": "/med-seg/samples/s0/overlay.webp",
    "gt": "/med-seg/samples/s0/gt.png",
    "pred": "/med-seg/samples/s0/pred.png",
    "edgeAttn": "/med-seg/samples/s0/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s0/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s0/dwt/ll.webp",
      "lh": "/med-seg/samples/s0/dwt/lh.webp",
      "hl": "/med-seg/samples/s0/dwt/hl.webp",
      "hh": "/med-seg/samples/s0/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQABAAAsBMJYgCdADJGHUV0AAA/upZLPEtvHYSormKnlnfxWjszDGpzYK4HRHMK/5Tpkpc6lKAvtydmzjQcnUZNsMFHAAA",
      "overlay": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoQABAAAsBMJbACdHMAApwp3uSgAP70vYD+27mfW4dmkP71rDzeJo1MXkxLqycHhpsl85gqiYnDQ19xF29ZlaD0FJ9Zoi+MelfRzpn3mwWlAMdE6/KzadWo6TcPUxVsz7D9s4yXeutP1CZsAAA="
    }
  },
  {
    "id": "s100",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s100/input.webp",
    "overlay": "/med-seg/samples/s100/overlay.webp",
    "gt": "/med-seg/samples/s100/gt.png",
    "pred": "/med-seg/samples/s100/pred.png",
    "edgeAttn": "/med-seg/samples/s100/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s100/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s100/dwt/ll.webp",
      "lh": "/med-seg/samples/s100/dwt/lh.webp",
      "hl": "/med-seg/samples/s100/dwt/hl.webp",
      "hh": "/med-seg/samples/s100/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQABAAAsBMJZACdAD1rbNy8agAAM4+tWXtCf/32LM0Yq8pqbNRL7lBmPYxq/imwKaqsLcjlWfntwooRDdXCEGpqE3SfqfygAA=",
      "overlay": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQABAAAsBMJbACdGaAlgAC4r/XBoAA/uaF5DQ6pgi9JIkP77xidnnvh7BSilbxvilSxGtGX9t5uQi0zKi76hj5jb4oFO3int+O1X6i8xMAyVQJWoWX9GEE7S0BqFgsu0wAAA=="
    }
  },
  {
    "id": "s200",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s200/input.webp",
    "overlay": "/med-seg/samples/s200/overlay.webp",
    "gt": "/med-seg/samples/s200/gt.png",
    "pred": "/med-seg/samples/s200/pred.png",
    "edgeAttn": "/med-seg/samples/s200/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s200/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s200/dwt/ll.webp",
      "lh": "/med-seg/samples/s200/dwt/lh.webp",
      "hl": "/med-seg/samples/s200/dwt/hl.webp",
      "hh": "/med-seg/samples/s200/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQABAAAsBMJbACdACTWvtUoYAA/piRsoqDLbs/OwhMjinNpV2O/U57i/RnwUeavL7zMiuOo+hXBnn3Oi871XuUBsOhuGZ69aWzZd/mb8KPUk/AAAA=",
      "overlay": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAgCdASoQABAAAsBMJbACdFQAuwADx9M2ANKIAP7OwhGlD/XyI+fZzBTHTFkk/s7071X/8Nowgs4wpERRTvnyMMjVsVOZwJLPcWio/a/VIv5zX8RCgs2EzANQvOx+AjU2yVsYKAOX1eMvmAA="
    }
  },
  {
    "id": "s300",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s300/input.webp",
    "overlay": "/med-seg/samples/s300/overlay.webp",
    "gt": "/med-seg/samples/s300/gt.png",
    "pred": "/med-seg/samples/s300/pred.png",
    "edgeAttn": "/med-seg/samples/s300/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s300/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s300/dwt/ll.webp",
      "lh": "/med-seg/samples/s300/dwt/lh.webp",
      "hl": "/med-seg/samples/s300/dwt/hl.webp",
      "hh": "/med-seg/samples/s300/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoQABAAAsBMJZACdAD0fts6GOKAAP7Tn3zG4geuGtZkyZOf4TsyJtLWl+96gJdpxyeW7bv26s3apvgAAAA=",
      "overlay": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoQABAAAsBMJbACdAD0fykowAAA/rmWsMDli/QeGSYjGPMg5Hb9awLZYBk9AAAA"
    }
  },
  {
    "id": "s400",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s400/input.webp",
    "overlay": "/med-seg/samples/s400/overlay.webp",
    "gt": "/med-seg/samples/s400/gt.png",
    "pred": "/med-seg/samples/s400/pred.png",
    "edgeAttn": "/med-seg/samples/s400/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s400/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s400/dwt/ll.webp",
      "lh": "/med-seg/samples/s400/dwt/lh.webp",
      "hl": "/med-seg/samples/s400/dwt/hl.webp",
      "hh": "/med-seg/samples/s400/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQABAAAsBMJZgCdAD7FT0MF/QAAP3SPJnKHlyPVYZLtvRCjvo7yrUJayL1+TW4maeRjz+yF5ut2Cm/bvI7CG7JkAA=",
      "overlay": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACQAgCdASoQABAAAsBMJbACdFQAmisE10gbcu5mgAD+2UNhl43rSL+tF/qPtmsMYKQx2BX42RAieNXC73ibdJy16LuuvNyhdVGDIvIqET4f6HGAiNoUgYOjI10tL2Xy+AXiHxSUrk0fXtuuTdOr2K2UAAA="
    }
  },
  {
    "id": "s500",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s500/input.webp",
    "overlay": "/med-seg/samples/s500/overlay.webp",
    "gt": "/med-seg/samples/s500/gt.png",
    "pred": "/med-seg/samples/s500/pred.png",
    "edgeAttn": "/med-seg/samples/s500/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s500/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s500/dwt/ll.webp",
      "lh": "/med-seg/samples/s500/dwt/lh.webp",
      "hl": "/med-seg/samples/s500/dwt/hl.webp",
      "hh": "/med-seg/samples/s500/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQABAAAsBMJZACdAEPC5zoVnywAP7ThJemjqEdadPVef/btsdFLRmrcpaHWFfkbWkg/2j28z9yLgAA",
      "overlay": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQABAAAsBMJbACdAEPAAz+/2wAAP6cpWMX2EvWmbeSVf255HYQuqukWo3YRpbPDFf11JAA"
    }
  },
  {
    "id": "s600",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s600/input.webp",
    "overlay": "/med-seg/samples/s600/overlay.webp",
    "gt": "/med-seg/samples/s600/gt.png",
    "pred": "/med-seg/samples/s600/pred.png",
    "edgeAttn": "/med-seg/samples/s600/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s600/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s600/dwt/ll.webp",
      "lh": "/med-seg/samples/s600/dwt/lh.webp",
      "hl": "/med-seg/samples/s600/dwt/hl.webp",
      "hh": "/med-seg/samples/s600/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQABAAAsBMJQBOgCHfLq3FHkAA/uBQX1q8sM6MkTys49cXBLWh49fZwOTyphzODLLVT3IScQ8UHlw6dlhLwDLbYIAAAA==",
      "overlay": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABQAQCdASoQABAAAsBMJbAABDOAAP7qB5hAyNd3ZSGub+ogrm5Sv+2B/1r5s7ffgcAAAA=="
    }
  },
  {
    "id": "s700",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s700/input.webp",
    "overlay": "/med-seg/samples/s700/overlay.webp",
    "gt": "/med-seg/samples/s700/gt.png",
    "pred": "/med-seg/samples/s700/pred.png",
    "edgeAttn": "/med-seg/samples/s700/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s700/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s700/dwt/ll.webp",
      "lh": "/med-seg/samples/s700/dwt/lh.webp",
      "hl": "/med-seg/samples/s700/dwt/hl.webp",
      "hh": "/med-seg/samples/s700/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQABAAAsBMJbACdLoAAlMwSlbyZUAA/pnaZNhPAQO8ob+fL18mn1bIYt3ej9RiG5ZtPI14ZPH0yXPGCDagJU/LyV7/wZHujptTu2X/fFAAAA==",
      "overlay": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQABAAAsBMJbACdDiKwP2T1w4FdAAA/sGYaRDe/guFbibmZLGtWebOMohXZMeqZ+Y5A58ECZn5yBJFmz6Ifwmfu0csG7Sl8RSI4C3/vVjHu7/ZY/w180TuF1X4AA=="
    }
  },
  {
    "id": "s800",
    "w": 481,
    "h": 478,
    "input": "/med-seg/samples/s800/input.webp",
    "overlay": "/med-seg/samples/s800/overlay.webp",
    "gt": "/med-seg/samples/s800/gt.png",
    "pred": "/med-seg/samples/s800/pred.png",
    "edgeAttn": "/med-seg/samples/s800/edge_attn_preview.webp",
    "thumb": "/med-seg/samples/s800/thumb.webp",
    "dwt": {
      "ll": "/med-seg/samples/s800/dwt/ll.webp",
      "lh": "/med-seg/samples/s800/dwt/lh.webp",
      "hl": "/med-seg/samples/s800/dwt/hl.webp",
      "hh": "/med-seg/samples/s800/dwt/hh.webp"
    },
    "blur": {
      "input": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQABAAAsBMJbACdACjBaa7QAD+BL8tjdG4hX8q5hzHx8AadAzCASw7uPa19ei6NNfkTPIK+aqwAAAA",
      "overlay": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQABAAAsBMJbACdFQAu0AEJsvqBGi4AP7cdSLG0ADI1He4LbgdKtoRA+Tw+fpMaLkw8muFAyUwTtB4B4dKT+8Re1K2m7EK5fuTS0TpnjvfoHnMAZLXFXncm/NwEDy2AAA="
    }
  }
];
